### ISSUE TITLE
cannot import name NavigationToolbar2QTAgg in Qgis 2.16 Nodebo

### ISSUE THREAD

**Issue by blabarthe** [apryet/Qgridder#12]
Since Matplotlib 1.5.0 NavigationToolbar2QTAgg has been removed, thus Qgridder plugin cannot be loaded in Qgis 2.16 Nodebo. Do you know what to do to fix this bug ?
Best regards
Baptiste Labarthe

**Comment by till90** [comment]
Hey to solve this Problem rename the import command in the mplwidget.py data as follow:

from matplotlib.backends.backend_qt4agg import NavigationToolbar2QTAgg
to 
from matplotlib.backends.backend_qt4agg import NavigationToolbar2QT
works fine with my QGIS 2.18

Best regards
